"""Read-only browser checks against the installed Next/API stack; no mocks or writes."""
from pathlib import Path
import json,os
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1]
OUT=Path(os.environ.get('VERIFICATION_DIR',str(ROOT/'docs/verification/json-samples-300-2026-09-21')))
OUT.mkdir(parents=True,exist_ok=True)
checks=[]
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'),headless=True)
    context=browser.new_context(viewport={'width':1440,'height':1080},permissions=['clipboard-read','clipboard-write'])
    page=context.new_page();errors=[];page.on('pageerror',lambda exc:errors.append(str(exc)))
    page.goto('http://localhost:3500/codes',wait_until='networkidle')
    ui=page.frame_locator('iframe[title="알림 코드 대화 작업실"]')
    expect(ui.locator('#app')).to_be_visible()
    expect(ui.locator('[data-view=imports], #imports, #catalog-import, input[type=file]')).to_have_count(0)
    checks.append('엑셀·CSV 파일 가져오기 메뉴·버튼·입력 제거')
    before=page.request.get('http://localhost:3500/api/code-catalog/codes?status=all').json()
    ui.get_by_role('tab',name='전체 코드',exact=True).click()
    ui.locator('#catalog-namespace').select_option('demo')
    expect(ui.locator('#catalog-list tbody tr')).to_have_count(30)
    expect(ui.locator('#catalog-scope-note')).to_contain_text('실제 회사 목록과 분리')
    checks.append('실제 Next/API에서 JSON 샘플 300건 조회')
    ui.locator('#catalog-query').fill('EX-0201')
    ui.locator('#catalog-form').get_by_role('button',name='검색',exact=True).click()
    expect(ui.locator('#catalog-list tbody tr')).to_have_count(1)
    ui.locator('#catalog-list .catalog-code').click()
    expect(ui.locator('#catalog-detail')).to_contain_text('이미 가입된 휴대폰 번호입니다. 로그인해주세요.')
    ui.locator('#catalog-detail').get_by_role('button',name='복사',exact=True).click()
    expect(ui.locator('#catalog-detail').get_by_role('button',name='복사됨',exact=True)).to_be_visible()
    clipboard=page.evaluate('navigator.clipboard.readText()')
    assert 'EX-0201' in clipboard and '이미 가입된 휴대폰 번호입니다. 로그인해주세요.' in clipboard
    ui.locator('#catalog-detail').get_by_role('button',name='닫기',exact=True).click()
    checks.append('목록 검색·상세·실제 클립보드 복사')
    with page.expect_download() as info:ui.locator('#export').click()
    download=info.value;dest=OUT/'sample_catalog_300.json';download.save_as(str(dest))
    exported=json.loads(dest.read_text());assert exported['total']==300 and len(exported['items'])==300
    assert exported['synthetic'] and len({r['code'] for r in exported['items']})==300
    checks.append('샘플 JSON 300건 다운로드')
    ui.locator('#catalog-query').fill('');ui.locator('#catalog-status').select_option('all')
    ui.locator('#catalog-form').get_by_role('button',name='검색',exact=True).click()
    expect(ui.locator('#catalog-list tbody tr')).to_have_count(30)
    expect(ui.locator('#catalog-count')).to_contain_text('300개')
    ui.locator('#next').click();expect(ui.locator('#catalog-count')).to_contain_text('31–60')
    ui.locator('#previous').click();expect(ui.locator('#catalog-count')).to_contain_text('1–30')
    checks.append('300건 목록의 페이지 이동')
    page.screenshot(path=str(OUT/'live-full-catalog.png'),full_page=True)
    ui.locator('#catalog-status').select_option('retired');ui.locator('#catalog-form').get_by_role('button',name='검색',exact=True).click()
    expect(ui.locator('#catalog-list tbody tr')).to_have_count(21)
    expect(ui.locator('#catalog-list tbody .btn').first).to_be_disabled()
    checks.append('폐기 항목 필터·복사 차단')
    ui.get_by_role('tab',name='문구 비교',exact=True).click()
    ui.locator('#compare-message').fill('30초 이내에 인증해주세요.')
    ui.locator('#compare-form').get_by_role('button',name='문구 비교',exact=True).click()
    expect(ui.locator('#compare-results')).to_contain_text('조건 방향이 다릅니다.')
    checks.append('실제 API의 원문·규칙 비교: 이후/이내 차이')
    ui.get_by_role('tab',name='기획서 검토',exact=True).click()
    ui.locator('#review-text').fill('EX-0201\nEX-0901\nEX-9999\nAT-1923: 30초 이내에 인증해주세요.')
    ui.locator('#review-form').get_by_role('button',name='검토',exact=True).click()
    expect(ui.locator('#review-results .review-item')).to_have_count(4)
    expect(ui.locator('#review-results')).to_contain_text('미등록 코드: EX-9999')
    expect(ui.locator('#review-results')).to_contain_text('조건 방향이 다릅니다.')
    page.screenshot(path=str(OUT/'live-document-review.png'),full_page=True)
    checks.append('기획서 4줄 검토: 등록·폐기·미등록·조건 차이')
    ui.get_by_role('tab',name='변경 기록',exact=True).click()
    expect(ui.locator('#audit-list')).to_contain_text('변경 기록이 없습니다')
    ui.locator('#audit-refresh').click()
    checks.append('실제 변경 기록 조회·새로고침 (현재 0건)')
    page.set_viewport_size({'width':390,'height':844})
    ui.get_by_role('tab',name='전체 코드',exact=True).click()
    ui.locator('#catalog-status').select_option('all');ui.locator('#catalog-form').get_by_role('button',name='검색',exact=True).click()
    expect(ui.locator('#catalog-list tbody tr')).to_have_count(30)
    frame=next(f for f in page.frames if '/code-catalog/ui/' in f.url)
    assert not frame.evaluate('document.documentElement.scrollWidth>innerWidth')
    page.screenshot(path=str(OUT/'live-catalog-mobile.png'),full_page=True)
    checks.append('390px 모바일: 표 영역 안에서 스크롤, 문서 가로 넘침 없음')
    after=page.request.get('http://localhost:3500/api/code-catalog/codes?status=all').json()
    assert before==after
    assert not errors,errors
    checks.append('운영 목록·버전 불변, JavaScript 오류 0건')
    browser.close()
report={'passed':True,'url':'http://localhost:3500/codes','mocks':False,'external_ai_called':False,'checks':checks,'production_total':after['total'],'sample_total':300}
(OUT/'live-menus.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(report,ensure_ascii=False,indent=2))
