"""Render recorded live evaluation results; never generates or alters scores."""
import json
from pathlib import Path
P=Path(__file__).resolve().parents[1]/'docs/verification/catalog-quality-68'
s=json.loads((P/'summary.json').read_text());rows=json.loads((P/'results.json').read_text())
lines=['# 알림 코드 68개 실제 품질 평가','', '현재 로컬 앱 + 분리된 합성 DB 평가입니다. 공공 문서 68개 Q&A를 사용하는 원본 평가와 동일한 데이터셋이 아닙니다.','', '| 지표 | 결과 |','|---|---:|',f"| 평가 질문 | {s['completed']} / 68개 |",f"| AI 채점 평균 | {s['judge_average']:.1f} / 100 ({s['judged']}개 채점 성공 기준) |" if s['judge_average'] is not None else '| AI 채점 평균 | 산출 불가 |',f"| GOOD 판정 (70점 이상) | {s['good']} / 68개 |",f"| 검색 적중률 (대표 정답 포함) | {s['search_hit_count']}/68 ({s['search_hit_count']/68:.1%}) |",f"| 키워드 재현율 | {s['keyword_recall_all']:.1%} |",f"| 답변 오류 / 채점 오류 | {s['answer_errors']} / {s['judge_errors']} |",'', '## 평가 조건','', '- 로컬 E5 + 하이브리드 검색 + 한국어 리랭커, 초기 후보 20개/최종 8개. HyDE와 멀티쿼리 OFF. 설정 원본은 `settings.json`.','- 실제 검색과 대화 API를 사용합니다. 답변은 Command Code 경유 DeepSeek이며 채점도 동일 모델의 별도 호출입니다. 독립 모델 평가가 아니므로 자기평가 편향 가능성이 있습니다.','- 원본의 100점 루브릭(정확성40/완전성30/관련성20/무해성10)과 키워드 추출 코드를 재사용했습니다. 70점 이상을 GOOD으로 집계합니다.','- 원본의 검색 적중 기준(score>0.3) 대신, 사전에 정한 정답 코드가 반환 후보 안에 있는지 검사합니다. 따라서 원본의 적중률 수치와 직접 비교하지 않습니다.','- 키워드 재현율은 코드·원문·메뉴·조건으로 구성한 정답과 실제 AI 설명을 비교합니다. API 실패는 재현율0/검색미적중/GOOD아님으로 포함합니다. 채점 평균은 실제 유효 점수가 나온 건만 포함하고 채점 수를 함께 표시합니다.','- 12개 직접 작성 질문 + 56개 메뉴/조건 템플릿 질문. 메뉴·조건이 질문에 주어지므로 일반적인 자유 질문보다 쉬울 수 있습니다. 결과를 보고 정답을 바꾸지 않았습니다.','- 평가 중 모델·검색 설정은 변경하지 않았습니다. 대화는 demo 스코프에만 생성합니다. 운영 데이터는 삽입하지 않습니다.','- 2개 요청을 동시 실행했으므로 응답 시간은 동시 실행 환경의 관측값입니다. 과거 단일 요청 시간과 직접 비교하지 않습니다.','',f"운영 목록 조회값/버전 보존: {s.get('production_unchanged','실행 중')}. 반환 후보 원문 일치: {s['all_returned_originals_match']}.",'','## 개별 결과','','| 번호 | 질문 | 정답 | 순위 | AI 점수 | 상태 |','|---:|---|---|---:|---:|---|']
for r in rows:
 score=r.get('judge',{}).get('score','—');status=r.get('error_detail') or r.get('error') or r.get('judge_error') or ('GOOD' if isinstance(score,int) and score>=70 else 'PARTIAL' if isinstance(score,int) and score>=40 else 'FAIL')
 lines.append(f"| {r['id']} | {r['query'].replace('|','/')} | {r['expected_code']} | {r.get('rank') or '—'} | {score} | {str(status).replace('|','/').replace(chr(10),' ')} |")
lines+=['','## 재현 및 원자료','','실행: `python3 integration_tests/live_catalog_quality_68.py` (현재 설정된 공급자 실제 호출 비용 발생). 리포트 생성: `python3 integration_tests/report_catalog_quality_68.py`. 재실행하면 같은 경로의 평가 파일을 갱신하므로 이전 결과를 별도 보관해야 합니다.','','`dataset.json`: 실행 전 고정 정답. `results.json`: 답변·검색 trace·AI 채점 이유·오류. `summary.json`: 집계. `corpus.json`: 평가 대상 합성 DB 스냅샷.']
(P/'README.md').write_text('\n'.join(lines)+'\n')
print(json.dumps(s,ensure_ascii=False))
